package compf.core.engine.pokemon.effects;

public enum EffectTime {
    ROUND_STARTING, ROUND_ENDING, ATTACK, DEFEND, POKEMON_SWITCHED_IN,POKEMON_SWITCHED_OUT, POKEMON_DEFEATED,DELAYED_ATTACK, STATS_MODIFIED,INDIRECT_DAMAGE
}
