package compf.core.engine.pokemon.effects;

public enum EffectTime {
    ROUND_STARTING, ROUND_ENDING, ATTACK, DEFEND, POKEMON_SWITCHED, POKEMON_DEFEATED, BATTLE_STARTED, DELAYED_ATTACK, STATS_MODIFIED,INDIRECT_DAMAGE
}
