class NameConstants:
  Stats= " stats? "
  ByStages =r"by \d+ stages?"
  PhysicalAttack = "(?<!Special) Attack"
  PhysicalDefense="(?<!Special) Defense"
  SpecialAttack="Special Attack"
  SpecialDefense="Special Defense"
  Speed="Speed"
  Immune="immun"
  Chance= r"\d+% chance"
  NextTurn= r"next turn"
  MultipleTurns=  r"\d(-\d)? turns"
  MultipleTimes=r"\d(-\d)? times"
  DependentOnMaxHP= r"\d+/\d+ of its maximum HP"
  DependentOnCurrHP=r"current HP"
  DealsDamage="(D|d)eals damage"
  CriticalHit="critical hit"
  Recovers="recovers"
  OnSwitch="(O| o)n switch"
  Prevent="(P| p)revent"
  BasedOnType="-type"
  NoEffect="No additional effect"
  Paraylzed= "paralyze"
  Poisoned= "(p|P)oison( |ed|s)"
  Asleep="(a)?sleep"
  Confused= "(c|C)onfus"
  Burn= "(B|b)urn"
  Freeze="(F|f)reeze"
  Recoil="recoil"
  HeldItem="held item"
  PowerOrDamageDoubled ="(((p|P)ower)|(D|d)amage)? doubled?"
  Accuracy="(A|a)ccuracy"
  Evasiveness=  "(E|e)vasiveness"
  IfTarget= "(I|i)f the target"
  IfUser="(I|i)f the user"
  Multiplied="multiplied"



  NumberStages="NumberStages"
