/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package teambuilder

import compf.core.engine.pokemon.Pokemon

class Library {
    fun someLibraryMethod(): Boolean {
        val team=PokemonTeam()
        return true
    }
}

