name: test_genetic_workflow
on: push
jobs:
  test_genetic:
   runs-on: ubuntu-latest
   steps:
      - uses: actions/checkout@v1
      - name: My first step
        uses: ./.github/teambuilder_runner
      - name: git stuff
        run: |
          git config --global --add safe.directory /github/workspace
          git config --local user.email "actions@github.com"
          git config --local user.name "Github Actions"
          git checkout battlelog
          git add teamBuilder/*.txt
          git commit -m "added log"
          git push
