/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package teambuilder
import compf.core.engine.pokemon.PokePasteParser;
import compf.core.engine.SharedInformation
import kotlin.test.Test
import kotlin.test.assertTrue
import org.junit.jupiter.api.BeforeAll

class LibraryTest {
    companion object{
        @BeforeAll
        @JvmStatic
        public fun init(){
                SharedInformation.Instance.init()
        }
 
}
    @Test fun testPokePasteParser() {
        SharedInformation.Instance.init()
       val input=
"""metagross @ Weakness Policy  
Ability: Clear Body  
Level: 50  
EVs: 252 HP / 252 Atk / 4 SpD  
Adamant Nature  
- protect  
- Iron Head  
- Ice Punch  
- Stomping Tantrum  
""";
       val parser=PokePasteParser(input)

       parser.parse()
    }
}
